# GPU SETTINGS
GPU1: 0
GPU2: 1 # Not used if DATA_PARALLEL is False.
DATA_PARALLEL: False
N_GROUP: 1 # The number of groups

# DATA OPTIONS
INPUT_DIM: 3
DATA_PATH: /home/ysong/
DATASET: vangogh2photo # The name of a dataset located in DATA_PATH,
RESIZE: 216
CROP_SIZE: 216

# TRAINING SETTINGS
NUM_ITERS: 200001 # Artworks dataset: 200000 / CelebA dataset: 500000
BATCH_SIZE: 4
G_LR: 0.0001
D_LR: 0.0001
BETA1: 0.5
BETA2: 0.999
WEIGHT_DECAY: 0.0001
NUM_ITERS_DECAY: 100000 # Artworks dataset: 100000 / CelebA dataset: 200000
LR_POLICY: step
GAMMA: 0.5
STEP_SIZE: 10000 # Artworks dataset: 10000 / CelebA dataset: 50000
INIT: kaiming

LAMBDA_X_REC: 10.0
LAMBDA_X_CYC: 10.0
LAMBDA_C: 1.0
LAMBDA_S: 1.0
LAMBDA_W_REG: 0.001
LAMBDA_C_REG: 10.0

# MODEL OPTIONS
G:
  FIRST_DIM: 64
  CONTENT_DIM: 256 # The number of channels of the content feature.
  MLP_DIM: 256 # G:128 => 2, G:64 => 8, G:32 => 16, G:16 => 64, G:8 => 256, G:4 => 1024, G:2 => 2048 / The number of elements in each block diagonal (please refer to Fig.3(b) of the paper).
  BIAS_DIM: 256 # The dimension of s_B_mu (Please refer to Fig.3(c) of the paper).
  N_RES_BLOCKS: 8

D:
  FIRST_DIM: 64
  NORM: none
  ACTIVATION: lrelu
  N_LAYER: 4
  GAN_TYPE: lsgan
  NUM_SCALES: 3
  PAD_TYPE: mirror

# ETC
NUM_WORKERS: 0
SAVE_NAME: vangogh_svd_cond
SAVE_EVERY: 10000
MODEL_SAVE_PATH: models/

### Required to be altered when MODE is changed.
START: 0 # Start iterations. This is also used in designating an trained-iteration of a loaded model.
LOAD_MODEL: False # Set true if model parameters are not trained from scratch.
MODE: train # Set 'train' or 'test'. Note that LOAD_MODEL option needs to be True in the 'test' mode.